version: "3.8"

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./api/.env
    volumes:
      - ./api/config:/app/config
      - ./api/src:/app/src
      - ./api/package.json:/app/package.json
      - ./api/yarn.lock:/app/yarn.lock
      - ./api/.env:/app/.env
      - ./api/public/uploads:/app/public/uploads
    ports:
      - 1337:1337
    networks:
      - app-network

  internal-api:
    container_name: internal-api
    build:
      context: ./internal-api
      dockerfile: Dockerfile
    env_file: ./internal-api/.env
    ports:
      - 8080:8080
    networks:
      - app-network
    volumes:
      - ./internal-api:/app
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    networks:
      - app-network
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/config.yml

networks:
  app-network:
volumes:
  prometheus-data:
